Add missing limits.h header file
On CentOS/RedHat compilation fails with:
fsdapi.h:76:16: error: ‘HOST_NAME_MAX’ undeclared here (not in a function)
  char hostname[HOST_NAME_MAX + 1];